apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: c8ivzascn-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:dc09b3b41f2f10121921e7373f6f6c49fad0ab7c@sha256:1c997f968160a13c1f982d102840d31c30729a695ca226532fc9fdcfdb23d2ca
          name: container-image
